import type { ReviewResult, Issue, Severity, Decision } from '@stargazer/core';

const SEVERITY_EMOJI: Record<Severity, string> = {
  critical: '🔴',
  high: '🟠',
  medium: '🟡',
  low: '🔵',
};

const DECISION_TEXT: Record<Decision, string> = {
  approve: '✅ Approved',
  request_changes: '❌ Changes Requested',
  comment: '💬 Comment',
};

export function formatReview(review: ReviewResult): string {
  const lines: string[] = [];

  lines.push('# Code Review Results');
  lines.push('');

  lines.push(`**Decision:** ${DECISION_TEXT[review.decision]}`);
  lines.push('');

  lines.push('## Summary');
  lines.push('');
  lines.push(review.summary);
  lines.push('');

  if (review.issues.length === 0) {
    lines.push('## ✅ No Issues Found');
    lines.push('');
    lines.push('Great job! The code looks good.');
  } else {
    lines.push(`## Issues (${review.issues.length})`);
    lines.push('');

    const grouped = groupBySeverity(review.issues);

    for (const severity of ['critical', 'high', 'medium', 'low'] as Severity[]) {
      const issues = grouped[severity];
      if (issues.length > 0) {
        lines.push(`### ${SEVERITY_EMOJI[severity]} ${capitalize(severity)} (${issues.length})`);
        lines.push('');

        for (const issue of issues) {
          lines.push(formatIssue(issue));
          lines.push('');
        }
      }
    }
  }

  lines.push('---');
  lines.push('*Generated by Stargazer AI Reviewer*');

  return lines.join('\n');
}

function formatIssue(issue: Issue): string {
  const lines: string[] = [];

  lines.push(`**\`${issue.file}:${issue.line}\`**`);
  lines.push('');
  lines.push(issue.message);

  if (issue.suggestion) {
    lines.push('');
    lines.push(`> 💡 **Suggestion:** ${issue.suggestion}`);
  }

  if (issue.conventionRef) {
    lines.push('');
    lines.push(`> 📋 **Convention:** ${issue.conventionRef}`);
  }

  return lines.join('\n');
}

function groupBySeverity(issues: Issue[]): Record<Severity, Issue[]> {
  const grouped: Record<Severity, Issue[]> = {
    critical: [],
    high: [],
    medium: [],
    low: [],
  };

  for (const issue of issues) {
    grouped[issue.severity].push(issue);
  }

  return grouped;
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
