# pnpm workspace configuration
# Defines which directories contain packages in this monorepo

packages:
  # Applications (standalone apps, not publishable libraries)
  - "apps/*"

  # Publishable packages (@stargazer/core, @stargazer/cli, @stargazer/action)
  - "packages/*"

  # Internal tooling packages (@repo/typescript, @repo/eslint, etc.)
  - "packages/tooling/*"
